version: '3'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode
    # networks: 
    #   - internal

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
    # Uncomment to change startup options
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mongo
    # networks:
    #       - mongo-express
    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    # networks:
    #   - mongo-express
  
  apiserver:
    image: nginx
    volumes:
    - ../configs/nginx:/etc/nginx/conf.d:rw
    - ../web/json:/var/www:rw
    ports:
    - "8082:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    # networks: 
    #   - internal

volumes:
  mongodb-data:
# networks:
#   mongo-express:
#     driver: bridge
#   internal:
#     external: true